# Generated by Django 4.1 on 2024-05-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_owner', models.BooleanField(default=False)),
                ('team_staff', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_workers', to='task_board.team')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-team_owner', '-team_staff'),
            },
        ),
        migrations.AddField(
            model_name='team',
            name='worker',
            field=models.ManyToManyField(related_name='teams', through='task_board.TeamWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('1', 'Low Priority'), ('2', 'Mid Priority'), ('3', 'High Priority')], max_length=1)),
                ('status', models.CharField(choices=[('UA', 'Unassigned'), ('IP', 'In Progress'), ('IR', 'In Review'), ('D', 'Done')], max_length=2)),
                ('assignees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_board.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='task_board.tag')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_board.tasktype')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='task_board.team'),
        ),
        migrations.AddConstraint(
            model_name='teamworker',
            constraint=models.UniqueConstraint(fields=('team', 'worker'), name='unique_worker_in_team'),
        ),
    ]
